### ISSUE TITLE
Can't Remove Road Sticker Arrow

### ISSUE THREAD

**Issue by fauzie** [aftersans53228/Minecraft-AFRoads-Mod#6]
1. Placing 4x4 Road Block
2. Placing `aft_fabroads:arrow_left` above
3. Left click, menimize the arrow size
4. Left click again, it wont removed

I try using word editor and building wands still sticker wont removed. Affected to all arrow sticker.

Minecraft: 1.20.1 Creative Mode
Fabric API: 0.84.0

Mod File: aftersans53228-fabric-road-1.0.2+1.20.1Release-hotfix.jar

**Comment by aftersans53228** [comment]
Sorry for this issue, and now this problem was fixed.
You can download new version [there.](https://modrinth.com/mod/aftersans53228-fabric-road/version/L222KrN4).
Thank you for your feedback.
